name = "espidf_tinyusb_msc"
version = "0.1.0-dev"
website = "https://github.com/godunko/espidf_tinyusb_msc"
description = "Ada/ESP-IDF: USB Device Stack bindings, Mass Storage Class"
long-description = """
Ada bindings for the ESP-IDF `esp_tinyusb` component, wrapping the TinyUSB stack to enable USB Device capabilities on ESP32 microcontrollers.
"""

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "esp", "esp32", "espidf"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
espidf = "*"
espidf_tinyusb = "*"
espidf_wear_levelling = "*"
